CREATE TABLE "public"."worker_documents" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "worker_id" bigint NOT NULL,
    "document_type_id" bigint NOT NULL,
    "semester_id" bigint,
    "file_name" text NOT NULL,
    "storage_path" text NOT NULL,
    "mime_type" text NOT NULL,
    "file_size" bigint NOT NULL,
    "uploaded_by" uuid DEFAULT "auth"."uid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "worker_documents_file_size_check" CHECK (
        "file_size" > 0 AND "file_size" <= 10485760
    )
);

ALTER TABLE "public"."worker_documents" OWNER TO "postgres";

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_storage_path_key" UNIQUE ("storage_path");

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_document_type_id_fkey" FOREIGN KEY ("document_type_id") REFERENCES "public"."worker_document_types"("id");

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_semester_id_fkey" FOREIGN KEY ("semester_id") REFERENCES "public"."semesters"("id");

ALTER TABLE ONLY "public"."worker_documents"
    ADD CONSTRAINT "worker_documents_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "auth"."users"("id");

GRANT ALL ON TABLE "public"."worker_documents" TO "anon";
GRANT ALL ON TABLE "public"."worker_documents" TO "authenticated";
GRANT ALL ON TABLE "public"."worker_documents" TO "service_role";

GRANT ALL ON SEQUENCE "public"."worker_documents_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."worker_documents_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."worker_documents_id_seq" TO "service_role";
