CREATE TABLE "public"."worker_document_types" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "category_id" bigint NOT NULL,
    "name" text NOT NULL,
    "allows_multiple" boolean DEFAULT false NOT NULL,
    "sort_order" smallint DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."worker_document_types" OWNER TO "postgres";

ALTER TABLE ONLY "public"."worker_document_types"
    ADD CONSTRAINT "worker_document_types_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."worker_document_types"
    ADD CONSTRAINT "worker_document_types_category_id_name_key" UNIQUE ("category_id", "name");

ALTER TABLE ONLY "public"."worker_document_types"
    ADD CONSTRAINT "worker_document_types_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."worker_document_categories"("id");

GRANT ALL ON TABLE "public"."worker_document_types" TO "anon";
GRANT ALL ON TABLE "public"."worker_document_types" TO "authenticated";
GRANT ALL ON TABLE "public"."worker_document_types" TO "service_role";

GRANT ALL ON SEQUENCE "public"."worker_document_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."worker_document_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."worker_document_types_id_seq" TO "service_role";
