create extension if not exists "pgjwt" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."date_of_admissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date_of_admission" date,
    "type" character varying,
    "worker_id" bigint
      );


alter table "public"."date_of_admissions" enable row level security;


  create table "public"."degrees" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" character varying,
    "name" character varying
      );


alter table "public"."degrees" enable row level security;


  create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "year_of_admission" integer,
    "letter" character varying,
    "degree_id" bigint
      );


alter table "public"."groups" enable row level security;


  create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" character varying,
    "worker_id" bigint
      );


alter table "public"."roles" enable row level security;


  create table "public"."schedule_assignments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "weekday" character varying,
    "group_id" bigint,
    "subject_id" bigint,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "worker_id" bigint,
    "semester_id" bigint
      );


alter table "public"."schedule_assignments" enable row level security;


  create table "public"."schedule_teachers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "weekday" character varying,
    "activity" character varying,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "worker_id" bigint,
    "semester_id" bigint
      );


alter table "public"."schedule_teachers" enable row level security;


  create table "public"."semesters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "semester" character varying,
    "school_year" character varying
      );


alter table "public"."semesters" enable row level security;


  create table "public"."state_roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" character varying,
    "name_worker" character varying
      );


alter table "public"."state_roles" enable row level security;


  create table "public"."study_programs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "year" integer,
    "name" character varying
      );


alter table "public"."study_programs" enable row level security;


  create table "public"."subjects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "semester" character varying,
    "name" character varying,
    "credits" real,
    "hours_per_week" smallint,
    "hours_per_semester" smallint,
    "study_program_id" bigint,
    "degree_id" bigint
      );


alter table "public"."subjects" enable row level security;


  create table "public"."sustenance_plazas" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "sustenance" character varying,
    "payment_key" character varying,
    "plaza" character varying,
    "worker_id" bigint
      );


alter table "public"."sustenance_plazas" enable row level security;


  create table "public"."utilities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" character varying,
    "value" character varying
      );


alter table "public"."utilities" enable row level security;


  create table "public"."workers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "profile_picture" character varying,
    "street" character varying,
    "neighborhood" character varying,
    "post_code" character varying,
    "city" character varying,
    "state" character varying,
    "phone" character varying,
    "email" character varying,
    "RFC" character varying,
    "specialty" character varying,
    "type_worker" character varying,
    "function_performed" character varying,
    "observations" character varying,
    "status" smallint
      );


alter table "public"."workers" enable row level security;

CREATE UNIQUE INDEX date_of_admissions_pkey ON public.date_of_admissions USING btree (id);

CREATE UNIQUE INDEX degrees_pkey ON public.degrees USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX schedule_assignments_pkey ON public.schedule_assignments USING btree (id);

CREATE UNIQUE INDEX schedule_teachers_pkey ON public.schedule_teachers USING btree (id);

CREATE UNIQUE INDEX semesters_pkey ON public.semesters USING btree (id);

CREATE UNIQUE INDEX state_roles_pkey ON public.state_roles USING btree (id);

CREATE UNIQUE INDEX study_programs_pkey ON public.study_programs USING btree (id);

CREATE UNIQUE INDEX subject_pkey ON public.subjects USING btree (id);

CREATE UNIQUE INDEX sustenance_plazas_pkey ON public.sustenance_plazas USING btree (id);

CREATE UNIQUE INDEX utilities_pkey ON public.utilities USING btree (id);

CREATE UNIQUE INDEX workers_pkey ON public.workers USING btree (id);

alter table "public"."date_of_admissions" add constraint "date_of_admissions_pkey" PRIMARY KEY using index "date_of_admissions_pkey";

alter table "public"."degrees" add constraint "degrees_pkey" PRIMARY KEY using index "degrees_pkey";

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."schedule_assignments" add constraint "schedule_assignments_pkey" PRIMARY KEY using index "schedule_assignments_pkey";

alter table "public"."schedule_teachers" add constraint "schedule_teachers_pkey" PRIMARY KEY using index "schedule_teachers_pkey";

alter table "public"."semesters" add constraint "semesters_pkey" PRIMARY KEY using index "semesters_pkey";

alter table "public"."state_roles" add constraint "state_roles_pkey" PRIMARY KEY using index "state_roles_pkey";

alter table "public"."study_programs" add constraint "study_programs_pkey" PRIMARY KEY using index "study_programs_pkey";

alter table "public"."subjects" add constraint "subject_pkey" PRIMARY KEY using index "subject_pkey";

alter table "public"."sustenance_plazas" add constraint "sustenance_plazas_pkey" PRIMARY KEY using index "sustenance_plazas_pkey";

alter table "public"."utilities" add constraint "utilities_pkey" PRIMARY KEY using index "utilities_pkey";

alter table "public"."workers" add constraint "workers_pkey" PRIMARY KEY using index "workers_pkey";

alter table "public"."date_of_admissions" add constraint "date_of_admissions_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES public.workers(id) not valid;

alter table "public"."date_of_admissions" validate constraint "date_of_admissions_worker_id_fkey";

alter table "public"."groups" add constraint "groups_degree_id_fkey" FOREIGN KEY (degree_id) REFERENCES public.degrees(id) not valid;

alter table "public"."groups" validate constraint "groups_degree_id_fkey";

alter table "public"."roles" add constraint "roles_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES public.workers(id) not valid;

alter table "public"."roles" validate constraint "roles_worker_id_fkey";

alter table "public"."schedule_assignments" add constraint "schedule_assignments_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) not valid;

alter table "public"."schedule_assignments" validate constraint "schedule_assignments_group_id_fkey";

alter table "public"."schedule_assignments" add constraint "schedule_assignments_semester_id_fkey" FOREIGN KEY (semester_id) REFERENCES public.semesters(id) not valid;

alter table "public"."schedule_assignments" validate constraint "schedule_assignments_semester_id_fkey";

alter table "public"."schedule_assignments" add constraint "schedule_assignments_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES public.subjects(id) not valid;

alter table "public"."schedule_assignments" validate constraint "schedule_assignments_subject_id_fkey";

alter table "public"."schedule_assignments" add constraint "schedule_assignments_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES public.workers(id) not valid;

alter table "public"."schedule_assignments" validate constraint "schedule_assignments_worker_id_fkey";

alter table "public"."schedule_teachers" add constraint "schedule_teachers_semester_id_fkey" FOREIGN KEY (semester_id) REFERENCES public.semesters(id) not valid;

alter table "public"."schedule_teachers" validate constraint "schedule_teachers_semester_id_fkey";

alter table "public"."schedule_teachers" add constraint "schedule_teachers_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES public.workers(id) not valid;

alter table "public"."schedule_teachers" validate constraint "schedule_teachers_worker_id_fkey";

alter table "public"."subjects" add constraint "subject_degree_id_fkey" FOREIGN KEY (degree_id) REFERENCES public.degrees(id) not valid;

alter table "public"."subjects" validate constraint "subject_degree_id_fkey";

alter table "public"."subjects" add constraint "subject_study_program_id_fkey" FOREIGN KEY (study_program_id) REFERENCES public.study_programs(id) not valid;

alter table "public"."subjects" validate constraint "subject_study_program_id_fkey";

alter table "public"."sustenance_plazas" add constraint "sustenance_plazas_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES public.workers(id) not valid;

alter table "public"."sustenance_plazas" validate constraint "sustenance_plazas_worker_id_fkey";

grant delete on table "public"."date_of_admissions" to "anon";

grant insert on table "public"."date_of_admissions" to "anon";

grant references on table "public"."date_of_admissions" to "anon";

grant select on table "public"."date_of_admissions" to "anon";

grant trigger on table "public"."date_of_admissions" to "anon";

grant truncate on table "public"."date_of_admissions" to "anon";

grant update on table "public"."date_of_admissions" to "anon";

grant delete on table "public"."date_of_admissions" to "authenticated";

grant insert on table "public"."date_of_admissions" to "authenticated";

grant references on table "public"."date_of_admissions" to "authenticated";

grant select on table "public"."date_of_admissions" to "authenticated";

grant trigger on table "public"."date_of_admissions" to "authenticated";

grant truncate on table "public"."date_of_admissions" to "authenticated";

grant update on table "public"."date_of_admissions" to "authenticated";

grant delete on table "public"."date_of_admissions" to "service_role";

grant insert on table "public"."date_of_admissions" to "service_role";

grant references on table "public"."date_of_admissions" to "service_role";

grant select on table "public"."date_of_admissions" to "service_role";

grant trigger on table "public"."date_of_admissions" to "service_role";

grant truncate on table "public"."date_of_admissions" to "service_role";

grant update on table "public"."date_of_admissions" to "service_role";

grant delete on table "public"."degrees" to "anon";

grant insert on table "public"."degrees" to "anon";

grant references on table "public"."degrees" to "anon";

grant select on table "public"."degrees" to "anon";

grant trigger on table "public"."degrees" to "anon";

grant truncate on table "public"."degrees" to "anon";

grant update on table "public"."degrees" to "anon";

grant delete on table "public"."degrees" to "authenticated";

grant insert on table "public"."degrees" to "authenticated";

grant references on table "public"."degrees" to "authenticated";

grant select on table "public"."degrees" to "authenticated";

grant trigger on table "public"."degrees" to "authenticated";

grant truncate on table "public"."degrees" to "authenticated";

grant update on table "public"."degrees" to "authenticated";

grant delete on table "public"."degrees" to "service_role";

grant insert on table "public"."degrees" to "service_role";

grant references on table "public"."degrees" to "service_role";

grant select on table "public"."degrees" to "service_role";

grant trigger on table "public"."degrees" to "service_role";

grant truncate on table "public"."degrees" to "service_role";

grant update on table "public"."degrees" to "service_role";

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."schedule_assignments" to "anon";

grant insert on table "public"."schedule_assignments" to "anon";

grant references on table "public"."schedule_assignments" to "anon";

grant select on table "public"."schedule_assignments" to "anon";

grant trigger on table "public"."schedule_assignments" to "anon";

grant truncate on table "public"."schedule_assignments" to "anon";

grant update on table "public"."schedule_assignments" to "anon";

grant delete on table "public"."schedule_assignments" to "authenticated";

grant insert on table "public"."schedule_assignments" to "authenticated";

grant references on table "public"."schedule_assignments" to "authenticated";

grant select on table "public"."schedule_assignments" to "authenticated";

grant trigger on table "public"."schedule_assignments" to "authenticated";

grant truncate on table "public"."schedule_assignments" to "authenticated";

grant update on table "public"."schedule_assignments" to "authenticated";

grant delete on table "public"."schedule_assignments" to "service_role";

grant insert on table "public"."schedule_assignments" to "service_role";

grant references on table "public"."schedule_assignments" to "service_role";

grant select on table "public"."schedule_assignments" to "service_role";

grant trigger on table "public"."schedule_assignments" to "service_role";

grant truncate on table "public"."schedule_assignments" to "service_role";

grant update on table "public"."schedule_assignments" to "service_role";

grant delete on table "public"."schedule_teachers" to "anon";

grant insert on table "public"."schedule_teachers" to "anon";

grant references on table "public"."schedule_teachers" to "anon";

grant select on table "public"."schedule_teachers" to "anon";

grant trigger on table "public"."schedule_teachers" to "anon";

grant truncate on table "public"."schedule_teachers" to "anon";

grant update on table "public"."schedule_teachers" to "anon";

grant delete on table "public"."schedule_teachers" to "authenticated";

grant insert on table "public"."schedule_teachers" to "authenticated";

grant references on table "public"."schedule_teachers" to "authenticated";

grant select on table "public"."schedule_teachers" to "authenticated";

grant trigger on table "public"."schedule_teachers" to "authenticated";

grant truncate on table "public"."schedule_teachers" to "authenticated";

grant update on table "public"."schedule_teachers" to "authenticated";

grant delete on table "public"."schedule_teachers" to "service_role";

grant insert on table "public"."schedule_teachers" to "service_role";

grant references on table "public"."schedule_teachers" to "service_role";

grant select on table "public"."schedule_teachers" to "service_role";

grant trigger on table "public"."schedule_teachers" to "service_role";

grant truncate on table "public"."schedule_teachers" to "service_role";

grant update on table "public"."schedule_teachers" to "service_role";

grant delete on table "public"."semesters" to "anon";

grant insert on table "public"."semesters" to "anon";

grant references on table "public"."semesters" to "anon";

grant select on table "public"."semesters" to "anon";

grant trigger on table "public"."semesters" to "anon";

grant truncate on table "public"."semesters" to "anon";

grant update on table "public"."semesters" to "anon";

grant delete on table "public"."semesters" to "authenticated";

grant insert on table "public"."semesters" to "authenticated";

grant references on table "public"."semesters" to "authenticated";

grant select on table "public"."semesters" to "authenticated";

grant trigger on table "public"."semesters" to "authenticated";

grant truncate on table "public"."semesters" to "authenticated";

grant update on table "public"."semesters" to "authenticated";

grant delete on table "public"."semesters" to "service_role";

grant insert on table "public"."semesters" to "service_role";

grant references on table "public"."semesters" to "service_role";

grant select on table "public"."semesters" to "service_role";

grant trigger on table "public"."semesters" to "service_role";

grant truncate on table "public"."semesters" to "service_role";

grant update on table "public"."semesters" to "service_role";

grant delete on table "public"."state_roles" to "anon";

grant insert on table "public"."state_roles" to "anon";

grant references on table "public"."state_roles" to "anon";

grant select on table "public"."state_roles" to "anon";

grant trigger on table "public"."state_roles" to "anon";

grant truncate on table "public"."state_roles" to "anon";

grant update on table "public"."state_roles" to "anon";

grant delete on table "public"."state_roles" to "authenticated";

grant insert on table "public"."state_roles" to "authenticated";

grant references on table "public"."state_roles" to "authenticated";

grant select on table "public"."state_roles" to "authenticated";

grant trigger on table "public"."state_roles" to "authenticated";

grant truncate on table "public"."state_roles" to "authenticated";

grant update on table "public"."state_roles" to "authenticated";

grant delete on table "public"."state_roles" to "service_role";

grant insert on table "public"."state_roles" to "service_role";

grant references on table "public"."state_roles" to "service_role";

grant select on table "public"."state_roles" to "service_role";

grant trigger on table "public"."state_roles" to "service_role";

grant truncate on table "public"."state_roles" to "service_role";

grant update on table "public"."state_roles" to "service_role";

grant delete on table "public"."study_programs" to "anon";

grant insert on table "public"."study_programs" to "anon";

grant references on table "public"."study_programs" to "anon";

grant select on table "public"."study_programs" to "anon";

grant trigger on table "public"."study_programs" to "anon";

grant truncate on table "public"."study_programs" to "anon";

grant update on table "public"."study_programs" to "anon";

grant delete on table "public"."study_programs" to "authenticated";

grant insert on table "public"."study_programs" to "authenticated";

grant references on table "public"."study_programs" to "authenticated";

grant select on table "public"."study_programs" to "authenticated";

grant trigger on table "public"."study_programs" to "authenticated";

grant truncate on table "public"."study_programs" to "authenticated";

grant update on table "public"."study_programs" to "authenticated";

grant delete on table "public"."study_programs" to "service_role";

grant insert on table "public"."study_programs" to "service_role";

grant references on table "public"."study_programs" to "service_role";

grant select on table "public"."study_programs" to "service_role";

grant trigger on table "public"."study_programs" to "service_role";

grant truncate on table "public"."study_programs" to "service_role";

grant update on table "public"."study_programs" to "service_role";

grant delete on table "public"."subjects" to "anon";

grant insert on table "public"."subjects" to "anon";

grant references on table "public"."subjects" to "anon";

grant select on table "public"."subjects" to "anon";

grant trigger on table "public"."subjects" to "anon";

grant truncate on table "public"."subjects" to "anon";

grant update on table "public"."subjects" to "anon";

grant delete on table "public"."subjects" to "authenticated";

grant insert on table "public"."subjects" to "authenticated";

grant references on table "public"."subjects" to "authenticated";

grant select on table "public"."subjects" to "authenticated";

grant trigger on table "public"."subjects" to "authenticated";

grant truncate on table "public"."subjects" to "authenticated";

grant update on table "public"."subjects" to "authenticated";

grant delete on table "public"."subjects" to "service_role";

grant insert on table "public"."subjects" to "service_role";

grant references on table "public"."subjects" to "service_role";

grant select on table "public"."subjects" to "service_role";

grant trigger on table "public"."subjects" to "service_role";

grant truncate on table "public"."subjects" to "service_role";

grant update on table "public"."subjects" to "service_role";

grant delete on table "public"."sustenance_plazas" to "anon";

grant insert on table "public"."sustenance_plazas" to "anon";

grant references on table "public"."sustenance_plazas" to "anon";

grant select on table "public"."sustenance_plazas" to "anon";

grant trigger on table "public"."sustenance_plazas" to "anon";

grant truncate on table "public"."sustenance_plazas" to "anon";

grant update on table "public"."sustenance_plazas" to "anon";

grant delete on table "public"."sustenance_plazas" to "authenticated";

grant insert on table "public"."sustenance_plazas" to "authenticated";

grant references on table "public"."sustenance_plazas" to "authenticated";

grant select on table "public"."sustenance_plazas" to "authenticated";

grant trigger on table "public"."sustenance_plazas" to "authenticated";

grant truncate on table "public"."sustenance_plazas" to "authenticated";

grant update on table "public"."sustenance_plazas" to "authenticated";

grant delete on table "public"."sustenance_plazas" to "service_role";

grant insert on table "public"."sustenance_plazas" to "service_role";

grant references on table "public"."sustenance_plazas" to "service_role";

grant select on table "public"."sustenance_plazas" to "service_role";

grant trigger on table "public"."sustenance_plazas" to "service_role";

grant truncate on table "public"."sustenance_plazas" to "service_role";

grant update on table "public"."sustenance_plazas" to "service_role";

grant delete on table "public"."utilities" to "anon";

grant insert on table "public"."utilities" to "anon";

grant references on table "public"."utilities" to "anon";

grant select on table "public"."utilities" to "anon";

grant trigger on table "public"."utilities" to "anon";

grant truncate on table "public"."utilities" to "anon";

grant update on table "public"."utilities" to "anon";

grant delete on table "public"."utilities" to "authenticated";

grant insert on table "public"."utilities" to "authenticated";

grant references on table "public"."utilities" to "authenticated";

grant select on table "public"."utilities" to "authenticated";

grant trigger on table "public"."utilities" to "authenticated";

grant truncate on table "public"."utilities" to "authenticated";

grant update on table "public"."utilities" to "authenticated";

grant delete on table "public"."utilities" to "service_role";

grant insert on table "public"."utilities" to "service_role";

grant references on table "public"."utilities" to "service_role";

grant select on table "public"."utilities" to "service_role";

grant trigger on table "public"."utilities" to "service_role";

grant truncate on table "public"."utilities" to "service_role";

grant update on table "public"."utilities" to "service_role";

grant delete on table "public"."workers" to "anon";

grant insert on table "public"."workers" to "anon";

grant references on table "public"."workers" to "anon";

grant select on table "public"."workers" to "anon";

grant trigger on table "public"."workers" to "anon";

grant truncate on table "public"."workers" to "anon";

grant update on table "public"."workers" to "anon";

grant delete on table "public"."workers" to "authenticated";

grant insert on table "public"."workers" to "authenticated";

grant references on table "public"."workers" to "authenticated";

grant select on table "public"."workers" to "authenticated";

grant trigger on table "public"."workers" to "authenticated";

grant truncate on table "public"."workers" to "authenticated";

grant update on table "public"."workers" to "authenticated";

grant delete on table "public"."workers" to "service_role";

grant insert on table "public"."workers" to "service_role";

grant references on table "public"."workers" to "service_role";

grant select on table "public"."workers" to "service_role";

grant trigger on table "public"."workers" to "service_role";

grant truncate on table "public"."workers" to "service_role";

grant update on table "public"."workers" to "service_role";


  create policy "Enable delete for authenticated users only"
  on "public"."date_of_admissions"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."date_of_admissions"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."date_of_admissions"
  as permissive
  for select
  to public
using (true);



  create policy "Enable updatefor authenticated users only"
  on "public"."date_of_admissions"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."degrees"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert access for all users"
  on "public"."groups"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."groups"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."roles"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."roles"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable create access for all users"
  on "public"."schedule_assignments"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable delete access for all users"
  on "public"."schedule_assignments"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."schedule_assignments"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."schedule_assignments"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable create access for all users"
  on "public"."schedule_teachers"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable delete access for all users"
  on "public"."schedule_teachers"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."schedule_teachers"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."schedule_teachers"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable create access for all users"
  on "public"."semesters"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."semesters"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."state_roles"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."state_roles"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."study_programs"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."subjects"
  as permissive
  for select
  to public
using (true);



  create policy "Enable delete access for all users"
  on "public"."sustenance_plazas"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."sustenance_plazas"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."sustenance_plazas"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."sustenance_plazas"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."utilities"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."utilities"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."workers"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update access for all users"
  on "public"."workers"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Allow delete pictures 1pmf6kr_0"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'profile_pictures'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow delete pictures 1pmf6kr_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'profile_pictures'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow update pictures 1pmf6kr_0"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'profile_pictures'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow update pictures 1pmf6kr_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'profile_pictures'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow upload pictures 1pmf6kr_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'profile_pictures'::text) AND (auth.role() = 'authenticated'::text)));



