-- Durable reconciliation for worker-document Storage objects.
--
-- Metadata deletion remains the user-visible source of truth, but every
-- committed worker_documents DELETE now creates a server-only cleanup
-- obligation in the same database transaction. Storage objects themselves
-- must still be deleted through the Storage API, never by deleting rows from
-- storage.objects.

create schema if not exists private authorization postgres;
revoke all on schema private from public;

create table public.worker_document_storage_cleanup_queue (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  worker_id bigint not null,
  source_document_id bigint,
  enqueued_at timestamp with time zone not null default now(),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_attempt_at timestamp with time zone,
  last_error text check (
    last_error is null
    or last_error in (
      'reference_check_failed',
      'path_still_referenced',
      'storage_exists_check_failed',
      'storage_remove_failed',
      'queue_update_failed'
    )
  ),
  resolved_at timestamp with time zone,
  constraint worker_document_storage_cleanup_queue_path_not_blank
    check (length(btrim(storage_path)) > 0),
  constraint worker_document_storage_cleanup_queue_worker_positive
    check (worker_id > 0)
);

comment on table public.worker_document_storage_cleanup_queue is
  'Service-role-only retry ledger for Storage paths whose worker_documents metadata was deleted.';
comment on column public.worker_document_storage_cleanup_queue.storage_path is
  'Private worker_documents bucket path; never expose this table directly to app clients.';

create index worker_document_storage_cleanup_queue_pending_idx
  on public.worker_document_storage_cleanup_queue (worker_id, enqueued_at, id)
  where resolved_at is null;

alter table public.worker_document_storage_cleanup_queue enable row level security;

-- The queue is deliberately not a client data surface. RLS has no anon or
-- authenticated policies and grants are service-role-only.
revoke all on table public.worker_document_storage_cleanup_queue
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.worker_document_storage_cleanup_queue
  to service_role;

revoke all on sequence public.worker_document_storage_cleanup_queue_id_seq
  from public, anon, authenticated;
grant usage, select
  on sequence public.worker_document_storage_cleanup_queue_id_seq
  to service_role;

create or replace function private.enqueue_worker_document_storage_cleanup()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.storage_path is null or length(btrim(old.storage_path)) = 0 then
    return old;
  end if;

  insert into public.worker_document_storage_cleanup_queue (
    storage_path,
    worker_id,
    source_document_id
  )
  values (
    old.storage_path,
    old.worker_id,
    old.id
  )
  on conflict (storage_path) do update
  set worker_id = excluded.worker_id,
      source_document_id = excluded.source_document_id,
      enqueued_at = now(),
      attempt_count = 0,
      last_attempt_at = null,
      last_error = null,
      resolved_at = null;

  return old;
end;
$$;

alter function private.enqueue_worker_document_storage_cleanup() owner to postgres;
revoke all on function private.enqueue_worker_document_storage_cleanup()
  from public, anon, authenticated;

create trigger enqueue_worker_document_storage_cleanup
after delete on public.worker_documents
for each row
execute function private.enqueue_worker_document_storage_cleanup();

-- Migration postconditions: fail loudly rather than leave a partially
-- exposed operational queue.
do $postconditions$
declare
  v_rls_enabled boolean;
  v_policy_count integer;
  v_trigger_count integer;
  v_function_security_definer boolean;
begin
  select c.relrowsecurity
  into v_rls_enabled
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'worker_document_storage_cleanup_queue';

  if v_rls_enabled is distinct from true then
    raise exception 'Cleanup queue postcondition failed: RLS is not enabled';
  end if;

  select count(*)
  into v_policy_count
  from pg_policies
  where schemaname = 'public'
    and tablename = 'worker_document_storage_cleanup_queue';

  if v_policy_count <> 0 then
    raise exception 'Cleanup queue postcondition failed: expected zero client RLS policies, found %', v_policy_count;
  end if;

  if has_table_privilege('anon', 'public.worker_document_storage_cleanup_queue', 'SELECT')
     or has_table_privilege('anon', 'public.worker_document_storage_cleanup_queue', 'INSERT')
     or has_table_privilege('anon', 'public.worker_document_storage_cleanup_queue', 'UPDATE')
     or has_table_privilege('anon', 'public.worker_document_storage_cleanup_queue', 'DELETE')
     or has_table_privilege('authenticated', 'public.worker_document_storage_cleanup_queue', 'SELECT')
     or has_table_privilege('authenticated', 'public.worker_document_storage_cleanup_queue', 'INSERT')
     or has_table_privilege('authenticated', 'public.worker_document_storage_cleanup_queue', 'UPDATE')
     or has_table_privilege('authenticated', 'public.worker_document_storage_cleanup_queue', 'DELETE') then
    raise exception 'Cleanup queue postcondition failed: anon/authenticated retain direct table privileges';
  end if;

  select count(*)
  into v_trigger_count
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'worker_documents'
    and t.tgname = 'enqueue_worker_document_storage_cleanup'
    and not t.tgisinternal
    and t.tgenabled <> 'D';

  if v_trigger_count <> 1 then
    raise exception 'Cleanup queue postcondition failed: expected one enabled delete trigger, found %', v_trigger_count;
  end if;

  select p.prosecdef
  into v_function_security_definer
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'private'
    and p.proname = 'enqueue_worker_document_storage_cleanup'
    and pg_get_function_identity_arguments(p.oid) = '';

  if v_function_security_definer is distinct from true then
    raise exception 'Cleanup queue postcondition failed: private trigger function is not SECURITY DEFINER';
  end if;

  if has_function_privilege('anon', 'private.enqueue_worker_document_storage_cleanup()', 'EXECUTE')
     or has_function_privilege('authenticated', 'private.enqueue_worker_document_storage_cleanup()', 'EXECUTE') then
    raise exception 'Cleanup queue postcondition failed: client role can execute private trigger function directly';
  end if;
end
$postconditions$;
