

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."date_of_admissions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date_of_admission" "date",
    "type" character varying,
    "worker_id" bigint
);


ALTER TABLE "public"."date_of_admissions" OWNER TO "postgres";


ALTER TABLE "public"."date_of_admissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."date_of_admissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."degrees" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "code" character varying,
    "name" character varying
);


ALTER TABLE "public"."degrees" OWNER TO "postgres";


ALTER TABLE "public"."degrees" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."degrees_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."groups" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "year_of_admission" integer,
    "letter" character varying,
    "degree_id" bigint
);


ALTER TABLE "public"."groups" OWNER TO "postgres";


ALTER TABLE "public"."groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" character varying,
    "worker_id" bigint
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


COMMENT ON TABLE "public"."roles" IS 'Administrative college roles';



ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."schedule_assignments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "weekday" character varying,
    "group_id" bigint,
    "subject_id" bigint,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "worker_id" bigint,
    "semester_id" bigint
);


ALTER TABLE "public"."schedule_assignments" OWNER TO "postgres";


COMMENT ON TABLE "public"."schedule_assignments" IS 'Asignación de horarios escolares';



ALTER TABLE "public"."schedule_assignments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."schedule_assignments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."schedule_teachers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "weekday" character varying,
    "activity" character varying,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "worker_id" bigint,
    "semester_id" bigint
);


ALTER TABLE "public"."schedule_teachers" OWNER TO "postgres";


COMMENT ON TABLE "public"."schedule_teachers" IS 'Horario de actividades de los maestros';



ALTER TABLE "public"."schedule_teachers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."schedule_teachers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."semesters" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "semester" character varying,
    "school_year" character varying
);


ALTER TABLE "public"."semesters" OWNER TO "postgres";


ALTER TABLE "public"."semesters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."semesters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."state_roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" character varying,
    "name_worker" character varying
);


ALTER TABLE "public"."state_roles" OWNER TO "postgres";


COMMENT ON TABLE "public"."state_roles" IS 'Education political state roles';



ALTER TABLE "public"."state_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."state_roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."study_programs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "year" integer,
    "name" character varying
);


ALTER TABLE "public"."study_programs" OWNER TO "postgres";


ALTER TABLE "public"."study_programs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."study_programs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subjects" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "semester" character varying,
    "name" character varying,
    "credits" real,
    "hours_per_week" smallint,
    "hours_per_semester" smallint,
    "study_program_id" bigint,
    "degree_id" bigint
);


ALTER TABLE "public"."subjects" OWNER TO "postgres";


ALTER TABLE "public"."subjects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subject_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sustenance_plazas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sustenance" character varying,
    "payment_key" character varying,
    "plaza" character varying,
    "worker_id" bigint
);


ALTER TABLE "public"."sustenance_plazas" OWNER TO "postgres";


COMMENT ON TABLE "public"."sustenance_plazas" IS 'Tipo de plaza y clave';



ALTER TABLE "public"."sustenance_plazas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sustenance_plazas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."utilities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" character varying,
    "value" character varying
);


ALTER TABLE "public"."utilities" OWNER TO "postgres";


COMMENT ON TABLE "public"."utilities" IS 'Tabla con datos editables para agregarse a documentos';



ALTER TABLE "public"."utilities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."utilities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "profile_picture" character varying,
    "street" character varying,
    "neighborhood" character varying,
    "post_code" character varying,
    "city" character varying,
    "state" character varying,
    "phone" character varying,
    "email" character varying,
    "RFC" character varying,
    "specialty" character varying,
    "type_worker" character varying,
    "function_performed" character varying,
    "observations" character varying,
    "status" smallint
);


ALTER TABLE "public"."workers" OWNER TO "postgres";


ALTER TABLE "public"."workers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."date_of_admissions"
    ADD CONSTRAINT "date_of_admissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."degrees"
    ADD CONSTRAINT "degrees_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."schedule_assignments"
    ADD CONSTRAINT "schedule_assignments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."schedule_teachers"
    ADD CONSTRAINT "schedule_teachers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."semesters"
    ADD CONSTRAINT "semesters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."state_roles"
    ADD CONSTRAINT "state_roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."study_programs"
    ADD CONSTRAINT "study_programs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subject_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sustenance_plazas"
    ADD CONSTRAINT "sustenance_plazas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."utilities"
    ADD CONSTRAINT "utilities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workers"
    ADD CONSTRAINT "workers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."date_of_admissions"
    ADD CONSTRAINT "date_of_admissions_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_degree_id_fkey" FOREIGN KEY ("degree_id") REFERENCES "public"."degrees"("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id");



ALTER TABLE ONLY "public"."schedule_assignments"
    ADD CONSTRAINT "schedule_assignments_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id");



ALTER TABLE ONLY "public"."schedule_assignments"
    ADD CONSTRAINT "schedule_assignments_semester_id_fkey" FOREIGN KEY ("semester_id") REFERENCES "public"."semesters"("id");



ALTER TABLE ONLY "public"."schedule_assignments"
    ADD CONSTRAINT "schedule_assignments_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id");



ALTER TABLE ONLY "public"."schedule_assignments"
    ADD CONSTRAINT "schedule_assignments_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id");



ALTER TABLE ONLY "public"."schedule_teachers"
    ADD CONSTRAINT "schedule_teachers_semester_id_fkey" FOREIGN KEY ("semester_id") REFERENCES "public"."semesters"("id");



ALTER TABLE ONLY "public"."schedule_teachers"
    ADD CONSTRAINT "schedule_teachers_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id");



ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subject_degree_id_fkey" FOREIGN KEY ("degree_id") REFERENCES "public"."degrees"("id");



ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subject_study_program_id_fkey" FOREIGN KEY ("study_program_id") REFERENCES "public"."study_programs"("id");



ALTER TABLE ONLY "public"."sustenance_plazas"
    ADD CONSTRAINT "sustenance_plazas_worker_id_fkey" FOREIGN KEY ("worker_id") REFERENCES "public"."workers"("id");



CREATE POLICY "Enable create access for all users" ON "public"."schedule_assignments" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable create access for all users" ON "public"."schedule_teachers" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable create access for all users" ON "public"."semesters" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable delete access for all users" ON "public"."schedule_assignments" FOR DELETE USING (true);



CREATE POLICY "Enable delete access for all users" ON "public"."schedule_teachers" FOR DELETE USING (true);



CREATE POLICY "Enable delete access for all users" ON "public"."sustenance_plazas" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users only" ON "public"."date_of_admissions" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert access for all users" ON "public"."groups" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."date_of_admissions" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."sustenance_plazas" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."date_of_admissions" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."degrees" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."groups" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."roles" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."schedule_assignments" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."schedule_teachers" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."semesters" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."state_roles" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."study_programs" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."subjects" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."sustenance_plazas" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."utilities" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."workers" FOR SELECT USING (true);



CREATE POLICY "Enable update access for all users" ON "public"."roles" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for all users" ON "public"."schedule_assignments" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for all users" ON "public"."schedule_teachers" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for all users" ON "public"."state_roles" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for all users" ON "public"."utilities" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for all users" ON "public"."workers" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable update for authenticated users only" ON "public"."sustenance_plazas" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable updatefor authenticated users only" ON "public"."date_of_admissions" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."date_of_admissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."degrees" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."groups" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."schedule_assignments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."schedule_teachers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."semesters" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."state_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."study_programs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subjects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sustenance_plazas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."utilities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."workers" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."date_of_admissions" TO "anon";
GRANT ALL ON TABLE "public"."date_of_admissions" TO "authenticated";
GRANT ALL ON TABLE "public"."date_of_admissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."date_of_admissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."date_of_admissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."date_of_admissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."degrees" TO "anon";
GRANT ALL ON TABLE "public"."degrees" TO "authenticated";
GRANT ALL ON TABLE "public"."degrees" TO "service_role";



GRANT ALL ON SEQUENCE "public"."degrees_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."degrees_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."degrees_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."groups" TO "anon";
GRANT ALL ON TABLE "public"."groups" TO "authenticated";
GRANT ALL ON TABLE "public"."groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."groups_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."schedule_assignments" TO "anon";
GRANT ALL ON TABLE "public"."schedule_assignments" TO "authenticated";
GRANT ALL ON TABLE "public"."schedule_assignments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."schedule_assignments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."schedule_assignments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."schedule_assignments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."schedule_teachers" TO "anon";
GRANT ALL ON TABLE "public"."schedule_teachers" TO "authenticated";
GRANT ALL ON TABLE "public"."schedule_teachers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."schedule_teachers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."schedule_teachers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."schedule_teachers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."semesters" TO "anon";
GRANT ALL ON TABLE "public"."semesters" TO "authenticated";
GRANT ALL ON TABLE "public"."semesters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."state_roles" TO "anon";
GRANT ALL ON TABLE "public"."state_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."state_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."state_roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."state_roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."state_roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."study_programs" TO "anon";
GRANT ALL ON TABLE "public"."study_programs" TO "authenticated";
GRANT ALL ON TABLE "public"."study_programs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."study_programs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."study_programs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."study_programs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."subjects" TO "anon";
GRANT ALL ON TABLE "public"."subjects" TO "authenticated";
GRANT ALL ON TABLE "public"."subjects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subject_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subject_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subject_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sustenance_plazas" TO "anon";
GRANT ALL ON TABLE "public"."sustenance_plazas" TO "authenticated";
GRANT ALL ON TABLE "public"."sustenance_plazas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sustenance_plazas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sustenance_plazas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sustenance_plazas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."utilities" TO "anon";
GRANT ALL ON TABLE "public"."utilities" TO "authenticated";
GRANT ALL ON TABLE "public"."utilities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."utilities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."utilities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."utilities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workers" TO "anon";
GRANT ALL ON TABLE "public"."workers" TO "authenticated";
GRANT ALL ON TABLE "public"."workers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workers_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






