CREATE TABLE "public"."worker_document_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "scope" text NOT NULL,
    "sort_order" smallint DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "worker_document_categories_scope_check" CHECK (
        "scope" = ANY (ARRAY['permanent'::text, 'semester'::text])
    )
);

ALTER TABLE "public"."worker_document_categories" OWNER TO "postgres";

ALTER TABLE ONLY "public"."worker_document_categories"
    ADD CONSTRAINT "worker_document_categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."worker_document_categories"
    ADD CONSTRAINT "worker_document_categories_name_key" UNIQUE ("name");

GRANT ALL ON TABLE "public"."worker_document_categories" TO "anon";
GRANT ALL ON TABLE "public"."worker_document_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."worker_document_categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."worker_document_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."worker_document_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."worker_document_categories_id_seq" TO "service_role";
